<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            // BERLINES
            [
                'brand' => 'Peugeot',
                'model' => '508',
                'year' => 2023,
                'type' => 'berline',
                'seats' => 5,
                'doors' => 4,
                'transmission' => 'automatique',
                'fuel_type' => 'diesel',
                'engine_power' => 130,
                'fuel_consumption' => 5.2,
                'trunk_capacity' => 487,
                'price_per_day' => 45.00,
                'price_per_week' => 280.00,
                'price_per_month' => 950.00,
                'deposit' => 500.00,
                'mileage' => 12000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Berline élégante et confortable, idéale pour les longs trajets.',
                'status' => 'available',
                'rating' => 4.7,
                'reviews_count' => 23,
                'rental_count' => 45
            ],
            [
                'brand' => 'Renault',
                'model' => 'Megane',
                'year' => 2022,
                'type' => 'berline',
                'seats' => 5,
                'doors' => 4,
                'transmission' => 'manuelle',
                'fuel_type' => 'essence',
                'engine_power' => 115,
                'fuel_consumption' => 6.1,
                'trunk_capacity' => 434,
                'price_per_day' => 35.00,
                'price_per_week' => 220.00,
                'price_per_month' => 750.00,
                'deposit' => 400.00,
                'mileage' => 18000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => true,
                'backup_camera' => false,
                'description' => 'Berline compacte et économique, parfaite pour la ville.',
                'status' => 'available',
                'rating' => 4.3,
                'reviews_count' => 18,
                'rental_count' => 32
            ],

            // SUV
            [
                'brand' => 'Peugeot',
                'model' => '3008',
                'year' => 2023,
                'type' => 'suv',
                'seats' => 5,
                'doors' => 5,
                'transmission' => 'automatique',
                'fuel_type' => 'hybride',
                'engine_power' => 225,
                'fuel_consumption' => 4.8,
                'trunk_capacity' => 520,
                'price_per_day' => 65.00,
                'price_per_week' => 400.00,
                'price_per_month' => 1350.00,
                'deposit' => 700.00,
                'mileage' => 8000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV moderne et spacieux, hybride rechargeable.',
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 31,
                'rental_count' => 54
            ],
            [
                'brand' => 'Renault',
                'model' => 'Captur',
                'year' => 2022,
                'type' => 'suv',
                'seats' => 5,
                'doors' => 5,
                'transmission' => 'automatique',
                'fuel_type' => 'diesel',
                'engine_power' => 115,
                'fuel_consumption' => 5.5,
                'trunk_capacity' => 455,
                'price_per_day' => 50.00,
                'price_per_week' => 310.00,
                'price_per_month' => 1050.00,
                'deposit' => 600.00,
                'mileage' => 15000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV compact et polyvalent, parfait pour la famille.',
                'status' => 'available',
                'rating' => 4.5,
                'reviews_count' => 27,
                'rental_count' => 41
            ],

            // CITADINES
            [
                'brand' => 'Peugeot',
                'model' => '208',
                'year' => 2023,
                'type' => 'citadine',
                'seats' => 5,
                'doors' => 5,
                'transmission' => 'manuelle',
                'fuel_type' => 'essence',
                'engine_power' => 100,
                'fuel_consumption' => 5.5,
                'trunk_capacity' => 311,
                'price_per_day' => 25.00,
                'price_per_week' => 150.00,
                'price_per_month' => 500.00,
                'deposit' => 300.00,
                'mileage' => 22000,
                'gps_available' => false,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => true,
                'backup_camera' => false,
                'description' => 'Citadine agile et économique, idéale pour la ville.',
                'status' => 'available',
                'rating' => 4.2,
                'reviews_count' => 42,
                'rental_count' => 78
            ],
            [
                'brand' => 'Renault',
                'model' => 'Clio',
                'year' => 2022,
                'type' => 'citadine',
                'seats' => 5,
                'doors' => 5,
                'transmission' => 'automatique',
                'fuel_type' => 'essence',
                'engine_power' => 90,
                'fuel_consumption' => 5.8,
                'trunk_capacity' => 300,
                'price_per_day' => 28.00,
                'price_per_week' => 170.00,
                'price_per_month' => 580.00,
                'deposit' => 300.00,
                'mileage' => 25000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Citadine populaire et fiable.',
                'status' => 'available',
                'rating' => 4.4,
                'reviews_count' => 56,
                'rental_count' => 89
            ],

            // MOTOS
            [
                'brand' => 'Yamaha',
                'model' => 'MT-07',
                'year' => 2023,
                'type' => 'moto',
                'seats' => 2,
                'doors' => null,
                'transmission' => 'manuelle',
                'fuel_type' => 'essence',
                'engine_power' => 75,
                'fuel_consumption' => 4.2,
                'trunk_capacity' => null,
                'price_per_day' => 55.00,
                'price_per_week' => 330.00,
                'price_per_month' => 1100.00,
                'deposit' => 800.00,
                'mileage' => 3500,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Moto sportive polyvalente, idéale pour tous les jours.',
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 19,
                'rental_count' => 28
            ],
            [
                'brand' => 'Honda',
                'model' => 'CB500F',
                'year' => 2022,
                'type' => 'moto',
                'seats' => 2,
                'doors' => null,
                'transmission' => 'manuelle',
                'fuel_type' => 'essence',
                'engine_power' => 47,
                'fuel_consumption' => 3.9,
                'trunk_capacity' => null,
                'price_per_day' => 50.00,
                'price_per_week' => 300.00,
                'price_per_month' => 1000.00,
                'deposit' => 700.00,
                'mileage' => 8000,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Moto fiable et économique.',
                'status' => 'available',
                'rating' => 4.6,
                'reviews_count' => 14,
                'rental_count' => 22
            ],

            // SCOOTERS
            [
                'brand' => 'Yamaha',
                'model' => 'NMAX 125',
                'year' => 2023,
                'type' => 'scooter',
                'seats' => 2,
                'doors' => null,
                'transmission' => 'automatique',
                'fuel_type' => 'essence',
                'engine_power' => 12,
                'fuel_consumption' => 2.2,
                'trunk_capacity' => 25,
                'price_per_day' => 20.00,
                'price_per_week' => 110.00,
                'price_per_month' => 380.00,
                'deposit' => 250.00,
                'mileage' => 5000,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Scooter pratique et économique pour la ville.',
                'status' => 'available',
                'rating' => 4.3,
                'reviews_count' => 38,
                'rental_count' => 67
            ],

            // CAMIONNETTES
            [
                'brand' => 'Renault',
                'model' => 'Master',
                'year' => 2022,
                'type' => 'camionnette',
                'seats' => 3,
                'doors' => 3,
                'transmission' => 'manuelle',
                'fuel_type' => 'diesel',
                'engine_power' => 135,
                'fuel_consumption' => 8.5,
                'trunk_capacity' => 8000,
                'price_per_day' => 70.00,
                'price_per_week' => 420.00,
                'price_per_month' => 1400.00,
                'deposit' => 1000.00,
                'mileage' => 45000,
                'gps_available' => true,
                'child_seat_available' => false,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Camionnette spacieuse pour déménagements et transports.',
                'status' => 'available',
                'rating' => 4.4,
                'reviews_count' => 16,
                'rental_count' => 34
            ],

            // VÉHICULES EN MAINTENANCE (exemples)
            [
                'brand' => 'Peugeot',
                'model' => '2008',
                'year' => 2021,
                'type' => 'suv',
                'seats' => 5,
                'doors' => 5,
                'transmission' => 'automatique',
                'fuel_type' => 'essence',
                'engine_power' => 130,
                'fuel_consumption' => 6.2,
                'trunk_capacity' => 434,
                'price_per_day' => 42.00,
                'price_per_week' => 260.00,
                'price_per_month' => 880.00,
                'deposit' => 500.00,
                'mileage' => 35000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => false,
                'description' => 'SUV compact en révision technique.',
                'status' => 'maintenance',
                'rating' => 4.1,
                'reviews_count' => 29,
                'rental_count' => 58
            ],

            // VÉHICULE LOUÉ (exemple)
            [
                'brand' => 'Renault',
                'model' => 'Arkana',
                'year' => 2023,
                'type' => 'suv',
                'seats' => 5,
                'doors' => 5,
                'transmission' => 'automatique',
                'fuel_type' => 'hybride',
                'engine_power' => 140,
                'fuel_consumption' => 5.1,
                'trunk_capacity' => 513,
                'price_per_day' => 58.00,
                'price_per_week' => 350.00,
                'price_per_month' => 1180.00,
                'deposit' => 650.00,
                'mileage' => 6000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV coupé hybride, actuellement loué.',
                'status' => 'rented',
                'rating' => 4.7,
                'reviews_count' => 12,
                'rental_count' => 18
            ]
        ];

        foreach ($vehicles as $vehicleData) {
            Vehicle::create($vehicleData);
        }

        $this->command->info('✅ ' . count($vehicles) . ' véhicules créés avec succès!');
    }
}
