<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        $vehicles = [
            // === BERLINES (car) ===
            [
                'brand' => 'Peugeot',
                'model' => '508',
                'type' => 'car',
                'year' => 2023,
                'registration_number' => 'AB-123-CD',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'doors' => 4,
                'engine_power' => 130,
                'fuel_consumption' => 5.2,
                'trunk_capacity' => 487,
                'price_per_day' => 45.00,
                'price_per_week' => 280.00,
                'price_per_month' => 950.00,
                'deposit' => 500.00,
                'mileage' => 12000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Berline élégante et confortable, idéale pour les longs trajets.',
                'status' => 'available',
                'rating' => 4.7,
                'reviews_count' => 23,
                'rental_count' => 45,
            ],
            [
                'brand' => 'Renault',
                'model' => 'Megane',
                'type' => 'car',
                'year' => 2022,
                'registration_number' => 'EF-456-GH',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 5,
                'doors' => 4,
                'engine_power' => 115,
                'fuel_consumption' => 6.1,
                'trunk_capacity' => 434,
                'price_per_day' => 35.00,
                'price_per_week' => 220.00,
                'price_per_month' => 750.00,
                'deposit' => 400.00,
                'mileage' => 18000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => true,
                'backup_camera' => false,
                'image_path' => 'images/vehicles/Renault-Megane.png',
                'description' => 'Berline compacte et économique, parfaite pour la ville.',
                'status' => 'available',
                'rating' => 4.3,
                'reviews_count' => 18,
                'rental_count' => 32,
            ],
            [
                'brand' => 'BMW',
                'model' => 'Série 3',
                'type' => 'car',
                'year' => 2024,
                'registration_number' => 'IJ-789-KL',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'doors' => 4,
                'engine_power' => 190,
                'fuel_consumption' => 5.8,
                'trunk_capacity' => 480,
                'price_per_day' => 85.00,
                'price_per_week' => 530.00,
                'price_per_month' => 1800.00,
                'deposit' => 900.00,
                'mileage' => 5000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Berline premium allemande, confort et performance.',
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 15,
                'rental_count' => 22,
            ],

            // === SUV ===
            [
                'brand' => 'Peugeot',
                'model' => '3008',
                'type' => 'suv',
                'year' => 2023,
                'registration_number' => 'MN-101-OP',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 225,
                'fuel_consumption' => 4.8,
                'trunk_capacity' => 520,
                'price_per_day' => 65.00,
                'price_per_week' => 400.00,
                'price_per_month' => 1350.00,
                'deposit' => 700.00,
                'mileage' => 8000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV moderne et spacieux, hybride rechargeable.',
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 31,
                'rental_count' => 54,
            ],
            [
                'brand' => 'Renault',
                'model' => 'Captur',
                'type' => 'suv',
                'year' => 2022,
                'registration_number' => 'QR-202-ST',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 115,
                'fuel_consumption' => 5.5,
                'trunk_capacity' => 455,
                'price_per_day' => 50.00,
                'price_per_week' => 310.00,
                'price_per_month' => 1050.00,
                'deposit' => 600.00,
                'mileage' => 15000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV compact et polyvalent, parfait pour la famille.',
                'status' => 'available',
                'rating' => 4.5,
                'reviews_count' => 27,
                'rental_count' => 41,
            ],
            [
                'brand' => 'Volkswagen',
                'model' => 'Tiguan',
                'type' => 'suv',
                'year' => 2023,
                'registration_number' => 'UV-303-WX',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 150,
                'fuel_consumption' => 5.9,
                'trunk_capacity' => 615,
                'price_per_day' => 72.00,
                'price_per_week' => 450.00,
                'price_per_month' => 1500.00,
                'deposit' => 800.00,
                'mileage' => 10000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV familial spacieux avec grand coffre.',
                'status' => 'available',
                'rating' => 4.6,
                'reviews_count' => 22,
                'rental_count' => 38,
            ],
            [
                'brand' => 'Toyota',
                'model' => 'RAV4',
                'type' => 'suv',
                'year' => 2024,
                'registration_number' => 'YZ-404-AB',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 218,
                'fuel_consumption' => 4.5,
                'trunk_capacity' => 580,
                'price_per_day' => 78.00,
                'price_per_week' => 490.00,
                'price_per_month' => 1650.00,
                'deposit' => 850.00,
                'mileage' => 3000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV hybride fiable et économique, idéal pour la famille.',
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 9,
                'rental_count' => 12,
            ],

            // === CITADINES (citycar) ===
            [
                'brand' => 'Peugeot',
                'model' => '208',
                'type' => 'citycar',
                'year' => 2023,
                'registration_number' => 'CD-505-EF',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 100,
                'fuel_consumption' => 5.5,
                'trunk_capacity' => 311,
                'price_per_day' => 25.00,
                'price_per_week' => 150.00,
                'price_per_month' => 500.00,
                'deposit' => 300.00,
                'mileage' => 22000,
                'gps_available' => false,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => true,
                'backup_camera' => false,
                'image_path' => 'images/vehicles/peugeot-208.png',
                'description' => 'Citadine agile et économique, idéale pour la ville.',
                'status' => 'available',
                'rating' => 4.2,
                'reviews_count' => 42,
                'rental_count' => 78,
            ],
            [
                'brand' => 'Renault',
                'model' => 'Clio',
                'type' => 'citycar',
                'year' => 2022,
                'registration_number' => 'GH-606-IJ',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 90,
                'fuel_consumption' => 5.8,
                'trunk_capacity' => 300,
                'price_per_day' => 28.00,
                'price_per_week' => 170.00,
                'price_per_month' => 580.00,
                'deposit' => 300.00,
                'mileage' => 25000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'image_path' => 'images/vehicles/renault-clio.png',
                'description' => 'Citadine populaire et fiable.',
                'status' => 'available',
                'rating' => 4.4,
                'reviews_count' => 56,
                'rental_count' => 89,
            ],
            [
                'brand' => 'Fiat',
                'model' => '500',
                'type' => 'citycar',
                'year' => 2023,
                'registration_number' => 'KL-707-MN',
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'seats' => 4,
                'doors' => 3,
                'engine_power' => 118,
                'fuel_consumption' => 0.0,
                'trunk_capacity' => 185,
                'price_per_day' => 32.00,
                'price_per_week' => 195.00,
                'price_per_month' => 650.00,
                'deposit' => 350.00,
                'mileage' => 8000,
                'gps_available' => true,
                'child_seat_available' => false,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'image_path' => 'images/vehicles/fiat-500.png',
                'description' => 'Citadine électrique stylée, zéro émission.',
                'status' => 'available',
                'rating' => 4.5,
                'reviews_count' => 28,
                'rental_count' => 45,
            ],
            [
                'brand' => 'Citroën',
                'model' => 'C3',
                'type' => 'citycar',
                'year' => 2023,
                'registration_number' => 'OP-808-QR',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 83,
                'fuel_consumption' => 5.2,
                'trunk_capacity' => 300,
                'price_per_day' => 22.00,
                'price_per_week' => 135.00,
                'price_per_month' => 450.00,
                'deposit' => 250.00,
                'mileage' => 15000,
                'gps_available' => false,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'image_path' => 'images/vehicles/Citroen-C3.png',
                'description' => 'Citadine confortable avec un design unique.',
                'status' => 'available',
                'rating' => 4.1,
                'reviews_count' => 35,
                'rental_count' => 62,
            ],

            // === MOTOS (motorcycle) ===
            [
                'brand' => 'Yamaha',
                'model' => 'MT-07',
                'type' => 'motorcycle',
                'year' => 2023,
                'registration_number' => 'ST-909-UV',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 2,
                'doors' => null,
                'engine_power' => 75,
                'fuel_consumption' => 4.2,
                'trunk_capacity' => null,
                'price_per_day' => 55.00,
                'price_per_week' => 330.00,
                'price_per_month' => 1100.00,
                'deposit' => 800.00,
                'mileage' => 3500,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Moto sportive polyvalente, idéale pour tous les jours.',
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 19,
                'rental_count' => 28,
            ],
            [
                'brand' => 'Honda',
                'model' => 'CB500F',
                'type' => 'motorcycle',
                'year' => 2022,
                'registration_number' => 'WX-010-YZ',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 2,
                'doors' => null,
                'engine_power' => 47,
                'fuel_consumption' => 3.9,
                'trunk_capacity' => null,
                'price_per_day' => 50.00,
                'price_per_week' => 300.00,
                'price_per_month' => 1000.00,
                'deposit' => 700.00,
                'mileage' => 8000,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Moto fiable et économique, parfaite pour débuter.',
                'status' => 'available',
                'rating' => 4.6,
                'reviews_count' => 14,
                'rental_count' => 22,
            ],
            [
                'brand' => 'Kawasaki',
                'model' => 'Z650',
                'type' => 'motorcycle',
                'year' => 2024,
                'registration_number' => 'AB-111-CD',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 2,
                'doors' => null,
                'engine_power' => 68,
                'fuel_consumption' => 4.0,
                'trunk_capacity' => null,
                'price_per_day' => 60.00,
                'price_per_week' => 360.00,
                'price_per_month' => 1200.00,
                'deposit' => 850.00,
                'mileage' => 2000,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'description' => 'Roadster sportif au design agressif.',
                'status' => 'available',
                'rating' => 4.7,
                'reviews_count' => 8,
                'rental_count' => 15,
            ],

            // === SCOOTERS ===
            [
                'brand' => 'Yamaha',
                'model' => 'NMAX 125',
                'type' => 'scooter',
                'year' => 2023,
                'registration_number' => 'EF-222-GH',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'seats' => 2,
                'doors' => null,
                'engine_power' => 12,
                'fuel_consumption' => 2.2,
                'trunk_capacity' => 25,
                'price_per_day' => 20.00,
                'price_per_week' => 110.00,
                'price_per_month' => 380.00,
                'deposit' => 250.00,
                'mileage' => 5000,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => false,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'image_path' => 'images/vehicles/Yamaha-NMAX-125.png',
                'description' => 'Scooter pratique et économique pour la ville.',
                'status' => 'available',
                'rating' => 4.3,
                'reviews_count' => 38,
                'rental_count' => 67,
            ],
            [
                'brand' => 'Honda',
                'model' => 'Forza 125',
                'type' => 'scooter',
                'year' => 2023,
                'registration_number' => 'IJ-333-KL',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'seats' => 2,
                'doors' => null,
                'engine_power' => 15,
                'fuel_consumption' => 2.0,
                'trunk_capacity' => 33,
                'price_per_day' => 25.00,
                'price_per_week' => 145.00,
                'price_per_month' => 480.00,
                'deposit' => 300.00,
                'mileage' => 3000,
                'gps_available' => false,
                'child_seat_available' => false,
                'bluetooth' => true,
                'air_conditioning' => false,
                'cruise_control' => false,
                'parking_sensors' => false,
                'backup_camera' => false,
                'image_path' => 'images/vehicles/Honda-Forza-125.png',
                'description' => 'Scooter GT haut de gamme, parfait pour les trajets quotidiens.',
                'status' => 'available',
                'rating' => 4.5,
                'reviews_count' => 21,
                'rental_count' => 40,
            ],

            // === CAMIONNETTES (van) ===
            [
                'brand' => 'Renault',
                'model' => 'Master',
                'type' => 'van',
                'year' => 2022,
                'registration_number' => 'MN-444-OP',
                'transmission' => 'manual',
                'fuel_type' => 'diesel',
                'seats' => 3,
                'doors' => 3,
                'engine_power' => 135,
                'fuel_consumption' => 8.5,
                'trunk_capacity' => 8000,
                'price_per_day' => 70.00,
                'price_per_week' => 420.00,
                'price_per_month' => 1400.00,
                'deposit' => 1000.00,
                'mileage' => 45000,
                'gps_available' => true,
                'child_seat_available' => false,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Camionnette spacieuse pour déménagements et transports.',
                'status' => 'available',
                'rating' => 4.4,
                'reviews_count' => 16,
                'rental_count' => 34,
            ],
            [
                'brand' => 'Citroën',
                'model' => 'Berlingo Van',
                'type' => 'van',
                'year' => 2023,
                'registration_number' => 'QR-555-ST',
                'transmission' => 'manual',
                'fuel_type' => 'diesel',
                'seats' => 3,
                'doors' => 4,
                'engine_power' => 100,
                'fuel_consumption' => 6.8,
                'trunk_capacity' => 3800,
                'price_per_day' => 48.00,
                'price_per_week' => 290.00,
                'price_per_month' => 980.00,
                'deposit' => 600.00,
                'mileage' => 20000,
                'gps_available' => true,
                'child_seat_available' => false,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Utilitaire compact et maniable, idéal pour les artisans.',
                'status' => 'available',
                'rating' => 4.3,
                'reviews_count' => 19,
                'rental_count' => 42,
            ],

            // === LUXE (luxury) ===
            [
                'brand' => 'Mercedes',
                'model' => 'Classe E',
                'type' => 'luxury',
                'year' => 2024,
                'registration_number' => 'UV-666-WX',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'doors' => 4,
                'engine_power' => 313,
                'fuel_consumption' => 3.0,
                'trunk_capacity' => 540,
                'price_per_day' => 150.00,
                'price_per_week' => 950.00,
                'price_per_month' => 3200.00,
                'deposit' => 1500.00,
                'mileage' => 2000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Berline de luxe avec toutes les options, confort absolu.',
                'status' => 'available',
                'rating' => 5.0,
                'reviews_count' => 6,
                'rental_count' => 8,
            ],
            [
                'brand' => 'Audi',
                'model' => 'A6',
                'type' => 'luxury',
                'year' => 2024,
                'registration_number' => 'YZ-777-AB',
                'transmission' => 'automatic',
                'fuel_type' => 'diesel',
                'seats' => 5,
                'doors' => 4,
                'engine_power' => 204,
                'fuel_consumption' => 5.5,
                'trunk_capacity' => 530,
                'price_per_day' => 130.00,
                'price_per_week' => 820.00,
                'price_per_month' => 2750.00,
                'deposit' => 1300.00,
                'mileage' => 4000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Berline premium avec intérieur raffiné et technologie avancée.',
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 11,
                'rental_count' => 14,
            ],

            // === CABRIOLETS (convertible) ===
            [
                'brand' => 'Mazda',
                'model' => 'MX-5',
                'type' => 'convertible',
                'year' => 2023,
                'registration_number' => 'CD-888-EF',
                'transmission' => 'manual',
                'fuel_type' => 'gasoline',
                'seats' => 2,
                'doors' => 2,
                'engine_power' => 184,
                'fuel_consumption' => 7.0,
                'trunk_capacity' => 130,
                'price_per_day' => 90.00,
                'price_per_week' => 560.00,
                'price_per_month' => 1900.00,
                'deposit' => 1000.00,
                'mileage' => 6000,
                'gps_available' => true,
                'child_seat_available' => false,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => false,
                'backup_camera' => true,
                'description' => 'Roadster décapotable, plaisir de conduite garanti.',
                'status' => 'available',
                'rating' => 4.8,
                'reviews_count' => 17,
                'rental_count' => 25,
            ],

            // === VÉHICULES ÉLECTRIQUES ===
            [
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'type' => 'car',
                'year' => 2024,
                'registration_number' => 'GH-999-IJ',
                'transmission' => 'automatic',
                'fuel_type' => 'electric',
                'seats' => 5,
                'doors' => 4,
                'engine_power' => 283,
                'fuel_consumption' => 0.0,
                'trunk_capacity' => 561,
                'price_per_day' => 95.00,
                'price_per_week' => 600.00,
                'price_per_month' => 2000.00,
                'deposit' => 1000.00,
                'mileage' => 4000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'Berline 100% électrique avec autopilot et écran tactile.',
                'status' => 'available',
                'rating' => 4.9,
                'reviews_count' => 34,
                'rental_count' => 50,
            ],

            // === EN MAINTENANCE / LOUÉ ===
            [
                'brand' => 'Peugeot',
                'model' => '2008',
                'type' => 'suv',
                'year' => 2021,
                'registration_number' => 'KL-100-MN',
                'transmission' => 'automatic',
                'fuel_type' => 'gasoline',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 130,
                'fuel_consumption' => 6.2,
                'trunk_capacity' => 434,
                'price_per_day' => 42.00,
                'price_per_week' => 260.00,
                'price_per_month' => 880.00,
                'deposit' => 500.00,
                'mileage' => 35000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => false,
                'description' => 'SUV compact en révision technique.',
                'status' => 'maintenance',
                'rating' => 4.1,
                'reviews_count' => 29,
                'rental_count' => 58,
            ],
            [
                'brand' => 'Renault',
                'model' => 'Arkana',
                'type' => 'suv',
                'year' => 2023,
                'registration_number' => 'OP-200-QR',
                'transmission' => 'automatic',
                'fuel_type' => 'hybrid',
                'seats' => 5,
                'doors' => 5,
                'engine_power' => 140,
                'fuel_consumption' => 5.1,
                'trunk_capacity' => 513,
                'price_per_day' => 58.00,
                'price_per_week' => 350.00,
                'price_per_month' => 1180.00,
                'deposit' => 650.00,
                'mileage' => 6000,
                'gps_available' => true,
                'child_seat_available' => true,
                'bluetooth' => true,
                'air_conditioning' => true,
                'cruise_control' => true,
                'parking_sensors' => true,
                'backup_camera' => true,
                'description' => 'SUV coupé hybride, actuellement loué.',
                'status' => 'rented',
                'rating' => 4.7,
                'reviews_count' => 12,
                'rental_count' => 18,
            ],
        ];

        $imageMap = [
            'audi-a6' => 'images/vehicles/Audi-A6.png',
            'bmw-serie-3' => 'images/vehicles/BMW-Serie-3.png',
            'citroen-berlingo-van' => 'images/vehicles/Citroen-Berlingo-Van.png',
            'citroen-c3' => 'images/vehicles/Citroen-C3.png',
            'fiat-500' => 'images/vehicles/fiat-500.png',
            'honda-cb500f' => 'images/vehicles/Honda-CB500F.png',
            'honda-forza-125' => 'images/vehicles/Honda-Forza-125.png',
            'kawasaki-z650' => 'images/vehicles/Kawasaki-Z650.png',
            'mazda-mx-5' => 'images/vehicles/Mazda-MX-5.png',
            'mercedes-classe-e' => 'images/vehicles/Mercedes-Classe-E.png',
            'peugeot-208' => 'images/vehicles/peugeot-208.png',
            'peugeot-3008' => 'images/vehicles/Peugeot-3008.png',
            'peugeot-508' => 'images/vehicles/peugeot-508.png',
            'renault-captur' => 'images/vehicles/Renault-Captur.png',
            'renault-clio' => 'images/vehicles/renault-clio.png',
            'renault-master' => 'images/vehicles/Renault-Master.png',
            'renault-megane' => 'images/vehicles/Renault-Megane.png',
            'tesla-model-3' => 'images/vehicles/Tesla-Model-3-18.png',
            'toyota-rav4' => 'images/vehicles/Toyota-RAV4.png',
            'volkswagen-tiguan' => 'images/vehicles/Volkswagen.png',
            'yamaha-mt-07' => 'images/vehicles/Yamaha-MT-07.png',
            'yamaha-nmax-125' => 'images/vehicles/Yamaha-NMAX-125.png',
        ];

        foreach ($vehicles as $vehicleData) {
            $vehicleKey = Str::slug(($vehicleData['brand'] ?? '').'-'.($vehicleData['model'] ?? ''));
            if (empty($vehicleData['image_path']) && isset($imageMap[$vehicleKey])) {
                $vehicleData['image_path'] = $imageMap[$vehicleKey];
            }

            Vehicle::create($vehicleData);
        }

        $this->command->info('✅ '.count($vehicles).' véhicules créés avec succès!');
    }
}
